version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 200000
      KAFKA_CREATE_TOPICS: "topic.adwork.messages:1:1,topic.adwork.comments:1:1,topic.adwork.ratings:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
